# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12901657db60a664e2d0918736f0b4906843487593a4012985b2cfc77502969b96e67bdbc25513ef64e8b51fbdc4535a20dc854f1db54cb574bbd041023260e4

test:
  secret_key_base: 1143b75b89005a3b83f859f29b30abf41f60bc8086f6b5292beb329f51f8b70cbd48a03012131c2122c68b7eca5d690506ae23a9a0a36de3e9dee5489c5c26f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
